import { useState } from 'react'
import { useAuthStore, usePageStore } from '../stores/index.js'
const API = import.meta.env.VITE_API_URL
const GENRES_MUSIC = ['Twarab','Sebene / Soukous','Afrobeats','Amapiano','Afrotrap / Rap','Coupé Décalé','Slam','Gospel / Religion','Traditionnel','Mindset / Motivation','Toirab','Sambé','Qasida']
const PODCAST_CATS = ['💡 Mindset','💼 Business','📚 Éducation','🎵 Musique','🗣️ Société','🏥 Santé','🔬 Tech','🌍 Actualités','⚽ Sport','🕌 Spiritualité']
const EMISSION_CATS = ['🎭 Culture','🗣️ Société','⚽ Sport','🎵 Musique','💼 Économie','🕌 Religion','🌱 Jeunesse','🔬 Tech','🌍 Actualités']
const COUNTRIES = [['KM','🇰🇲 Comores'],['MG','🇲🇬 Madagascar'],['TZ','🇹🇿 Tanzanie'],['RW','🇷🇼 Rwanda'],['CI',"🇨🇮 Côte d'Ivoire"],['NG','🇳🇬 Nigeria'],['CD','🇨🇩 RD Congo'],['SN','🇸🇳 Sénégal'],['GH','🇬🇭 Ghana'],['CM','🇨🇲 Cameroun']]
const LANGS = [['fr','Français'],['km','Shikomori'],['sw','Swahili'],['en','Anglais'],['ar','Arabe'],['mg','Malagasy']]
const CUR = ['KMF','USD','EUR','XOF','NGN']

function MonetBlock({ok,mode,setMode,form,set,preview=true,pvSec=10,setPvSec=null,showBoth=true}){
  const PM=[['free','🎁','Gratuit'],['buy','🛒','Vente'],['rent','⏳','Location']];if(showBoth)PM.push(['both','🔀','Vente+Location'])
  if(!ok)return(<div className="upload-section-box" style={{borderColor:'rgba(245,166,35,.25)',background:'rgba(245,166,35,.04)'}}><div className="upload-section-title">💰 Monétisation</div><div style={{display:'flex',alignItems:'center',gap:12,padding:'14px 16px',background:'rgba(245,166,35,.06)',border:'1px solid rgba(245,166,35,.2)',borderRadius:'var(--radius-sm)'}}><span style={{fontSize:24}}>🔒</span><div><div style={{fontSize:13,fontWeight:700,color:'var(--gold)',marginBottom:3}}>Compte non vérifié</div><div style={{fontSize:12,color:'var(--text2)',lineHeight:1.6}}>Seuls les vérifiés peuvent monétiser. Publication en <strong>gratuit uniquement</strong>. Demandez la vérification dans Paramètres.</div></div></div></div>)
  return(<div className="upload-section-box"><div className="upload-section-title">💰 Monétisation & Accès</div>
    <div className="pricing-modes">{PM.map(([id,ic,lb])=>(<div key={id} className={`pricing-mode${mode===id?' sel':''}`} onClick={()=>setMode(id)}><div className="pricing-mode-icon">{ic}</div><div className="pricing-mode-label">{lb}</div></div>))}</div>
    {(mode==='buy'||mode==='both')&&<div style={{marginBottom:14}}><label className="label">Prix de vente</label><div style={{display:'flex',gap:8}}><input className="input-field" type="number" value={form.sp||''} onChange={e=>set('sp',e.target.value)} placeholder="Ex: 2500" style={{flex:1}}/><select className="select-styled" value={form.sc||'KMF'} onChange={e=>set('sc',e.target.value)}>{CUR.map(c=><option key={c}>{c}</option>)}</select></div></div>}
    {(mode==='rent'||mode==='both')&&<div><label className="label" style={{marginBottom:10}}>Tarifs de location</label><div className="rental-grid">{[['rd','📅 Journalier','150'],['rw','📅 Hebdomadaire','600'],['rm','📅 Mensuel','1800']].map(([k,lb,ph])=>(<div key={k} className="rental-period-input"><div className="rental-period-label">{lb}</div><div style={{display:'flex',gap:6}}><input className="input-field" type="number" value={form[k]||''} onChange={e=>set(k,e.target.value)} placeholder={ph} style={{flex:1,fontSize:13}}/><select className="select-styled" style={{fontSize:12}}><option>KMF</option><option>USD</option></select></div></div>))}</div></div>}
    {preview&&mode!=='free'&&setPvSec&&<div style={{marginTop:16,padding:14,background:'rgba(245,166,35,.04)',border:'1px solid rgba(245,166,35,.15)',borderRadius:'var(--radius-sm)'}}><div style={{fontSize:12,fontWeight:700,color:'var(--text2)',marginBottom:8}}>🎧 Extrait gratuit</div><div style={{display:'flex',alignItems:'center',gap:14,flexWrap:'wrap'}}><input type="range" min="5" max="30" value={pvSec} onChange={e=>setPvSec(+e.target.value)} style={{width:120,accentColor:'var(--gold)'}}/><span style={{fontFamily:'Space Mono,monospace',fontSize:14,fontWeight:700,color:'var(--gold)'}}>{pvSec}s</span></div></div>}
  </div>)
}
function MonetFlux({ok,mode,setMode,form,set,pvSec,setPvSec}){
  if(!ok)return(<div className="upload-section-box" style={{borderColor:'rgba(245,166,35,.25)',background:'rgba(245,166,35,.04)'}}><div className="upload-section-title">💰 Accès au flux</div><div style={{display:'flex',alignItems:'center',gap:12,padding:14,background:'rgba(245,166,35,.06)',border:'1px solid rgba(245,166,35,.2)',borderRadius:'var(--radius-sm)'}}><span style={{fontSize:24}}>🔒</span><div><div style={{fontSize:13,fontWeight:700,color:'var(--gold)'}}>Non vérifié — gratuit uniquement</div></div></div></div>)
  const M=[['free','🎁','Gratuit','Accès libre'],['sub','💎','Abonnés','Réservé abonnés'],['paid','💳','Payant','Jour/semaine/mois/an']]
  return(<div className="upload-section-box"><div className="upload-section-title">💰 Accès au flux</div>
    <div className="pricing-modes">{M.map(([id,ic,lb,ds])=>(<div key={id} className={`pricing-mode${mode===id?' sel':''}`} onClick={()=>setMode(id)}><div className="pricing-mode-icon">{ic}</div><div className="pricing-mode-label">{lb}</div><div style={{fontSize:9,color:'var(--text3)',marginTop:2}}>{ds}</div></div>))}</div>
    {mode==='paid'&&<div style={{marginTop:14}}><label className="label" style={{marginBottom:10}}>Tarifs</label><div className="rental-grid" style={{gridTemplateColumns:'1fr 1fr'}}>{[['fd','📅 Jour','100'],['fw','📅 Semaine','500'],['fm','📅 Mois','1500'],['fy','📅 An','12000']].map(([k,lb,ph])=>(<div key={k} className="rental-period-input"><div className="rental-period-label">{lb}</div><div style={{display:'flex',gap:6}}><input className="input-field" type="number" value={form[k]||''} onChange={e=>set(k,e.target.value)} placeholder={ph} style={{flex:1,fontSize:13}}/><select className="select-styled" style={{fontSize:12}}><option>KMF</option><option>USD</option></select></div></div>))}</div></div>}
    {mode!=='free'&&<div style={{marginTop:16,padding:14,background:'rgba(245,166,35,.04)',border:'1px solid rgba(245,166,35,.15)',borderRadius:'var(--radius-sm)'}}><div style={{fontSize:12,fontWeight:700,color:'var(--text2)',marginBottom:8}}>🎧 Extrait gratuit</div><div style={{display:'flex',alignItems:'center',gap:14}}><input type="range" min="10" max="120" value={pvSec} onChange={e=>setPvSec(+e.target.value)} style={{width:140,accentColor:'var(--gold)'}}/><span style={{fontFamily:'Space Mono,monospace',fontSize:14,fontWeight:700,color:'var(--gold)'}}>{pvSec>=60?Math.floor(pvSec/60)+'min'+(pvSec%60>0?pvSec%60+'s':''):pvSec+'s'}</span></div></div>}
  </div>)
}

export default function Upload(){
  const{user}=useAuthStore();const{setPage}=usePageStore()
  const[tab,setTab]=useState('son'),[loading,setLoading]=useState(false),[progress,setProgress]=useState(0),[msg,setMsg]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState(false)
  const token=localStorage.getItem('waiichia_token'),ok=!!user?.is_verified
  const uf=async(file,ep)=>new Promise((res,rej)=>{const fd=new FormData();fd.append('file',file);const x=new XMLHttpRequest();x.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100))};x.onload=()=>{const d=JSON.parse(x.responseText);x.status>=400?rej(new Error(d.error)):res(d.url)};x.onerror=()=>rej(new Error('Erreur réseau'));x.open('POST',API+ep);x.setRequestHeader('Authorization','Bearer '+token);x.send(fd)})
  if(!user)return(<div style={{textAlign:'center',padding:60}}><div style={{fontSize:48,marginBottom:16}}>🔒</div><h2 style={{fontFamily:'Syne,sans-serif'}}>Connectez-vous pour publier</h2><button className="btn btn-primary" onClick={()=>setPage('login')} style={{marginTop:16}}>Se connecter</button></div>)
  if(success)return(<div style={{textAlign:'center',padding:80}}><div style={{fontSize:64,marginBottom:16}}>✅</div><div style={{fontFamily:'Syne,sans-serif',fontSize:24,fontWeight:800}}>Contenu publié !</div></div>)
  const T=[{id:'son',ic:'🎵',lb:'Son'},{id:'album',ic:'💿',lb:'Album'},{id:'podcast',ic:'🎙️',lb:'Podcast'},{id:'emission',ic:'📺',lb:'Émission'},{id:'media',ic:'📻',lb:'Flux Média'}]
  return(<div style={{maxWidth:720,paddingBottom:80}}><div className="page-title">📤 Publier du Contenu</div>
    <div className="tabs-bar" style={{marginBottom:24}}>{T.map(t=><button key={t.id} className={`tab-btn${tab===t.id?' active':''}`} onClick={()=>{setTab(t.id);setError('')}}>{t.ic} {t.lb}</button>)}</div>
    {error&&<div style={{background:'rgba(230,57,70,.1)',border:'1px solid rgba(230,57,70,.3)',borderRadius:'var(--radius-sm)',padding:'12px 16px',marginBottom:16,fontSize:13,color:'var(--red)'}}>⚠️ {error}</div>}
    {loading&&progress>0&&<div style={{marginBottom:16}}><div style={{display:'flex',justifyContent:'space-between',fontSize:12,color:'var(--text2)',marginBottom:6}}><span>{msg}</span><span style={{fontWeight:700,color:'var(--gold)'}}>{progress}%</span></div><div style={{background:'var(--border)',borderRadius:99,height:6,overflow:'hidden'}}><div style={{height:'100%',background:'linear-gradient(90deg,var(--gold),#e8920a)',width:progress+'%',transition:'width .3s'}}/></div></div>}
    {tab==='son'&&<FSon ok={ok} uf={uf} sL={setLoading} sE={setError} sM={setMsg} sP={setProgress} sS={setSuccess} sPage={setPage} tk={token}/>}
    {tab==='album'&&<FAlbum ok={ok}/>}
    {tab==='podcast'&&<FPodcast ok={ok}/>}
    {tab==='emission'&&<FEmission ok={ok}/>}
    {tab==='media'&&<FMedia ok={ok}/>}
  </div>)
}
function FSon({ok,uf,sL,sE,sM,sP,sS,sPage,tk}){
  const[af,setAf]=useState(null),[cf,setCf]=useState(null),[cp,setCp]=useState(''),[pm,setPm]=useState('free'),[lic,setLic]=useState('all'),[pvS,setPvS]=useState(10),[tags,setTags]=useState(['#twarab','#komori']),[ti,setTi]=useState('')
  const[f,sF]=useState({title:'',genre:'Twarab',country:'KM',language:'fr',bpm:'',key:'',mood:'',desc:'',feat:'',sp:'',sc:'KMF',rd:'',rw:'',rm:''})
  const s=(k,v)=>sF(p=>({...p,[k]:v}))
  const addTag=e=>{if(e.key==='Enter'||e.key===','){e.preventDefault();const t=ti.trim().replace(',','');if(t&&!tags.includes(t))setTags(p=>[...p,t.startsWith('#')?t:'#'+t]);setTi('')}}
  const submit=async()=>{if(!f.title)return sE('Titre requis');if(!af)return sE('Fichier audio requis');sL(true);sE('');sM('Upload audio...');sP(0);try{let au=await uf(af,'/api/upload/audio'),cu='';if(cf){sM('Upload pochette...');cu=await uf(cf,'/api/upload/cover')}sM('Publication...');const r=await fetch(API+'/api/tracks/',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+tk},body:JSON.stringify({title:f.title,description:f.desc,type:'music',genre:f.genre,country:f.country,language:f.language,access_type:pm==='free'?'free':'paid',sale_price:['buy','both'].includes(pm)?parseInt(f.sp)||0:0,rent_price_day:['rent','both'].includes(pm)?parseInt(f.rd)||0:0,preview_end_sec:pvS,audio_url_128:au,cover_url:cu||null,is_published:true,tags})});const d=await r.json();if(!r.ok)throw new Error(d.error);sS(true)}catch(e){sE(e.message)}sL(false)}
  const R=[['all','© Tous droits réservés','Utilisation interdite sans autorisation'],['cc','CC BY — Creative Commons','Libre avec attribution'],['nc','CC BY-NC','Pas d\'usage commercial']]
  return(<div className="upload-form-panel">
    <div className="upload-form-header"><div style={{fontSize:32}}>🎵</div><div><div style={{fontFamily:'Syne,sans-serif',fontWeight:800,fontSize:18}}>Publier un Son</div><div style={{fontSize:12,color:'var(--text2)'}}>Single, instrumental ou remix</div></div></div>
    <div className="upload-drop-zone" onClick={()=>document.getElementById('iS').click()}><input type="file" id="iS" accept=".mp3,.wav,.flac,.ogg,.aac" style={{display:'none'}} onChange={e=>{const x=e.target.files[0];if(x)setAf(x)}}/>{af?<div><div style={{fontSize:36,marginBottom:8}}>✅</div><div className="upload-drop-title">{af.name}</div><div className="upload-drop-sub">({(af.size/1048576).toFixed(1)} MB)</div></div>:<div><div className="upload-drop-icon">🎵</div><div className="upload-drop-title">Glissez votre fichier audio ici</div><div className="upload-drop-sub">MP3 · WAV · FLAC — Max 200 MB</div><button className="btn btn-primary btn-sm" style={{marginTop:14}}>Parcourir</button></div>}</div>
    <div className="form-group"><label className="label">🖼️ Pochette *</label><div className="cover-upload-row"><div className="cover-preview" onClick={()=>document.getElementById('cS').click()}><input type="file" id="cS" accept="image/*" style={{display:'none'}} onChange={e=>{const x=e.target.files[0];if(x){setCf(x);setCp(URL.createObjectURL(x))}}}/>{cp?<img src={cp} alt=""/>:<><span>+</span><div style={{fontSize:10,marginTop:4}}>Ajouter</div></>}</div><div style={{fontSize:12,color:'var(--text2)',lineHeight:1.7}}>Carré · 800×800px min · JPG/PNG</div></div></div>
    <div className="form-group"><label className="label">Titre *</label><input className="input-field" value={f.title} onChange={e=>s('title',e.target.value)} placeholder="Titre du son..."/></div>
    <div className="form-row"><div className="form-group"><label className="label">Genre</label><select className="select-styled" style={{width:'100%'}} value={f.genre} onChange={e=>s('genre',e.target.value)}>{GENRES_MUSIC.map(g=><option key={g}>{g}</option>)}</select></div><div className="form-group"><label className="label">Pays</label><select className="select-styled" style={{width:'100%'}} value={f.country} onChange={e=>s('country',e.target.value)}>{COUNTRIES.map(([c,l])=><option key={c} value={c}>{l}</option>)}</select></div></div>
    <div className="form-row" style={{gridTemplateColumns:'1fr 1fr 1fr'}}><div className="form-group"><label className="label">BPM</label><input className="input-field" type="number" value={f.bpm} onChange={e=>s('bpm',e.target.value)} placeholder="120"/></div><div className="form-group"><label className="label">Tonalité</label><select className="select-styled" style={{width:'100%'}} value={f.key} onChange={e=>s('key',e.target.value)}><option value="">--</option><option>Do (C)</option><option>Ré (D)</option><option>Mi (E)</option><option>Fa (F)</option><option>Sol (G)</option><option>La (A)</option><option>Si (B)</option></select></div><div className="form-group"><label className="label">Humeur</label><select className="select-styled" style={{width:'100%'}} value={f.mood} onChange={e=>s('mood',e.target.value)}><option value="">--</option><option>Joyeux</option><option>Mélancolique</option><option>Énergique</option><option>Spirituel</option><option>Romantique</option></select></div></div>
    <div className="form-group"><label className="label">Tags</label><div className="tag-input-wrap">{tags.map(t=><div key={t} className="tag-pill">{t} <span className="remove" onClick={()=>setTags(p=>p.filter(x=>x!==t))}>✕</span></div>)}<input className="tag-input" value={ti} onChange={e=>setTi(e.target.value)} onKeyDown={addTag} placeholder="Ajouter un tag..."/></div></div>
    <div className="form-group"><label className="label">🎤 Featuring</label><input className="input-field" value={f.feat} onChange={e=>s('feat',e.target.value)} placeholder="Rechercher un artiste..."/></div>
    <div className="form-group"><label className="label">Description / Paroles</label><textarea className="textarea-field" value={f.desc} onChange={e=>s('desc',e.target.value)} placeholder="Décrivez votre son..."/></div>
    <div className="upload-section-box" style={{borderColor:'rgba(245,166,35,.25)',background:'rgba(245,166,35,.04)'}}><div className="upload-section-title">🎧 Extrait gratuit</div><div style={{display:'flex',alignItems:'center',gap:14,flexWrap:'wrap'}}><span className="label" style={{margin:0}}>Durée</span><input type="range" min="5" max="20" value={pvS} onChange={e=>setPvS(+e.target.value)} style={{width:120,accentColor:'var(--gold)'}}/><span style={{fontFamily:'Space Mono,monospace',fontSize:14,fontWeight:700,color:'var(--gold)'}}>{pvS}s</span><span style={{fontSize:11,color:'var(--text3)'}}>Min 5s · Max 20s</span></div></div>
    <MonetBlock ok={ok} mode={pm} setMode={setPm} form={f} set={s} preview={false}/>
    <div className="upload-section-box"><div className="upload-section-title">⚖️ Droits & Licence</div><div style={{display:'flex',flexDirection:'column',gap:10}}>{R.map(([id,t,d])=><label key={id} style={{display:'flex',alignItems:'flex-start',gap:10,cursor:'pointer'}}><input type="radio" name="lic" checked={lic===id} onChange={()=>setLic(id)} style={{accentColor:'var(--gold)',marginTop:3}}/><div><div style={{fontSize:13,fontWeight:600}}>{t}</div><div style={{fontSize:11,color:'var(--text2)'}}>{d}</div></div></label>)}</div></div>
    <div className="upload-form-actions"><button className="btn btn-secondary" style={{padding:'13px 20px'}}>💾 Brouillon</button><button className="btn btn-primary" style={{flex:1,padding:13,fontSize:15}} onClick={submit}>🚀 Publier</button></div>
  </div>)
}
function FAlbum({ok}){
  const[cp,setCp]=useState(''),[pm,setPm]=useState('free'),[pvS,setPvS]=useState(15),[f,sF]=useState({sp:'',sc:'KMF',rd:'',rw:'',rm:''}),[tks,setTks]=useState([{t:''},{t:''}])
  const s=(k,v)=>sF(p=>({...p,[k]:v}))
  return(<div className="upload-form-panel">
    <div className="upload-form-header"><div style={{fontSize:32}}>💿</div><div><div style={{fontFamily:'Syne,sans-serif',fontWeight:800,fontSize:18}}>Créer un Album</div><div style={{fontSize:12,color:'var(--text2)'}}>Album, EP, mixtape ou compilation</div></div></div>
    <div className="form-group"><label className="label">🖼️ Pochette *</label><div className="cover-upload-row"><div className="cover-preview" onClick={()=>document.getElementById('cA').click()}><input type="file" id="cA" accept="image/*" style={{display:'none'}} onChange={e=>{const x=e.target.files[0];if(x)setCp(URL.createObjectURL(x))}}/>{cp?<img src={cp} alt=""/>:<><span>+</span><div style={{fontSize:10,marginTop:4}}>Ajouter</div></>}</div><div style={{fontSize:12,color:'var(--text2)'}}>Carré · 1000×1000px min</div></div></div>
    <div className="form-row"><div className="form-group" style={{flex:2}}><label className="label">Titre *</label><input className="input-field" placeholder="Titre album..."/></div><div className="form-group"><label className="label">Type</label><select className="select-styled" style={{width:'100%'}}><option>Album</option><option>EP</option><option>Mixtape</option><option>Compilation</option></select></div></div>
    <div className="form-row" style={{gridTemplateColumns:'1fr 1fr 1fr'}}><div className="form-group"><label className="label">Genre</label><select className="select-styled" style={{width:'100%'}}>{GENRES_MUSIC.slice(0,9).map(g=><option key={g}>{g}</option>)}</select></div><div className="form-group"><label className="label">Pays</label><select className="select-styled" style={{width:'100%'}}>{COUNTRIES.slice(0,6).map(([c,l])=><option key={c} value={c}>{l}</option>)}</select></div><div className="form-group"><label className="label">Année</label><input className="input-field" type="number" defaultValue="2026"/></div></div>
    <div className="form-group"><label className="label">Description</label><textarea className="textarea-field" placeholder="Parlez de cet album..."/></div>
    <div className="upload-section-box"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><div><div className="upload-section-title" style={{marginBottom:2}}>🎵 Pistes</div></div><button className="btn btn-outline btn-sm" onClick={()=>setTks(p=>[...p,{t:''}])}>+ Ajouter</button></div>
      {tks.map((_,i)=><div key={i} className="album-track-row"><div className="track-row-num">{i+1}</div><div className="track-row-body"><input className="input-field" placeholder="Titre piste *" style={{marginBottom:8}}/><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><label className="upload-mini-btn" style={{cursor:'pointer'}}>🎵 Audio<input type="file" accept="audio/*" style={{display:'none'}}/></label><input className="input-field" placeholder="Feat." style={{flex:1,minWidth:100}}/></div></div>{tks.length>1&&<button className="track-row-remove" onClick={()=>setTks(p=>p.filter((_,j)=>j!==i))}>✕</button>}</div>)}
      <div style={{marginTop:10,fontSize:11,color:'var(--text3)'}}>💡 Ajoutez des pistes plus tard depuis Mon Contenu.</div></div>
    <MonetBlock ok={ok} mode={pm} setMode={setPm} form={f} set={s} showBoth={true} preview={true} pvSec={pvS} setPvSec={setPvS}/>
    <div className="upload-section-box"><div className="upload-section-title">⚖️ Droits</div><div style={{display:'flex',flexDirection:'column',gap:10}}>{[['© Tous droits réservés','Interdite sans autorisation'],['CC BY — Creative Commons','Libre avec attribution']].map(([t,d],i)=><label key={i} style={{display:'flex',alignItems:'flex-start',gap:10,cursor:'pointer'}}><input type="radio" name="ra" defaultChecked={i===0} style={{accentColor:'var(--gold)',marginTop:3}}/><div><div style={{fontSize:13,fontWeight:600}}>{t}</div><div style={{fontSize:11,color:'var(--text2)'}}>{d}</div></div></label>)}</div></div>
    <div className="upload-form-actions"><button className="btn btn-secondary">💾 Brouillon</button><button className="btn btn-outline">📋 Sans pistes</button><button className="btn btn-primary" style={{flex:1,padding:13,fontSize:15}}>🚀 Publier</button></div>
  </div>)
}
function FPodcast({ok}){
  const[step,setStep]=useState(1),[cp,setCp]=useState(''),[eps,setEps]=useState([{}]),[pm,setPm]=useState('free'),[pvS,setPvS]=useState(15),[f,sF]=useState({sp:'',rd:'',rw:'',rm:''})
  const s=(k,v)=>sF(p=>({...p,[k]:v}))
  const Steps=()=><div className="upload-steps-bar">{[{n:1,l:'Série'},{n:2,l:'Épisodes'},{n:3,l:'Diffusion'}].map((x,i)=><div key={x.n} style={{display:'contents'}}>{i>0&&<div className="upload-step-sep"/>}<div className={`upload-step${step===x.n?' active':''}${step>x.n?' done':''}`} onClick={()=>setStep(x.n)}><span className="step-num">{step>x.n?'✓':x.n}</span><span>{x.l}</span></div></div>)}</div>
  return(<div className="upload-form-panel">
    <div className="upload-form-header"><div style={{fontSize:32}}>🎙️</div><div><div style={{fontFamily:'Syne,sans-serif',fontWeight:800,fontSize:18}}>Créer un Podcast</div><div style={{fontSize:12,color:'var(--text2)'}}>Série avec épisodes</div></div></div>
    <Steps/>
    {step===1&&<div>
      <div className="form-group"><label className="label">🖼️ Visuel *</label><div className="cover-upload-row"><div className="cover-preview" onClick={()=>document.getElementById('cP').click()}><input type="file" id="cP" accept="image/*" style={{display:'none'}} onChange={e=>{const x=e.target.files[0];if(x)setCp(URL.createObjectURL(x))}}/>{cp?<img src={cp} alt=""/>:<><span>+</span><div style={{fontSize:10,marginTop:4}}>Ajouter</div></>}</div><div style={{fontSize:12,color:'var(--text2)'}}>Carré · 1400×1400px</div></div></div>
      <div className="form-group"><label className="label">Nom *</label><input className="input-field" placeholder="Ex: Business Afrika..."/></div>
      <div className="form-row"><div className="form-group"><label className="label">Catégorie</label><select className="select-styled" style={{width:'100%'}}>{PODCAST_CATS.map(c=><option key={c}>{c}</option>)}</select></div><div className="form-group"><label className="label">Langue</label><select className="select-styled" style={{width:'100%'}}>{LANGS.map(([c,l])=><option key={c} value={c}>{l}</option>)}</select></div></div>
      <div className="form-row" style={{gridTemplateColumns:'1fr 1fr 1fr'}}><div className="form-group"><label className="label">Pays</label><select className="select-styled" style={{width:'100%'}}>{COUNTRIES.slice(0,6).map(([c,l])=><option key={c} value={c}>{l}</option>)}</select></div><div className="form-group"><label className="label">Fréquence</label><select className="select-styled" style={{width:'100%'}}><option>Hebdomadaire</option><option>Bi-hebdo</option><option>Mensuel</option><option>Irrégulier</option></select></div><div className="form-group"><label className="label">Accès</label><select className="select-styled" style={{width:'100%'}}><option>🔓 Public</option><option>🔒 Abonnés</option><option>🔀 Mixte</option></select></div></div>
      <div className="form-group"><label className="label">Description *</label><textarea className="textarea-field" rows="4" placeholder="Décrivez votre podcast..."/></div>
      <div style={{display:'flex',justifyContent:'flex-end',marginTop:18}}><button className="btn btn-primary" onClick={()=>setStep(2)}>Suivant →</button></div>
    </div>}
    {step===2&&<div>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><div><div style={{fontWeight:700,fontSize:15}}>Épisodes</div></div><button className="btn btn-outline btn-sm" onClick={()=>setEps(p=>[...p,{}])}>+ Épisode</button></div>
      {eps.map((_,i)=><div key={i} className="episode-block"><div className="episode-block-header"><div className="episode-num-badge">Ép. {i+1}</div><input className="input-field" placeholder="Titre *" style={{flex:1}}/>{eps.length>1&&<button className="episode-remove-btn" onClick={()=>setEps(p=>p.filter((_,j)=>j!==i))}>✕</button>}</div><div className="episode-block-body"><div className="upload-drop-zone" style={{padding:18,marginBottom:12}}><div style={{fontSize:20}}>🎙️</div><div style={{fontSize:13,fontWeight:600,marginTop:6}}>Fichier audio</div></div><div className="form-row" style={{gridTemplateColumns:'1fr 1fr 1fr'}}><div className="form-group"><label className="label" style={{fontSize:11}}>N°</label><input className="input-field" type="number" defaultValue={i+1}/></div><div className="form-group"><label className="label" style={{fontSize:11}}>Saison</label><input className="input-field" type="number" defaultValue="1"/></div><div className="form-group"><label className="label" style={{fontSize:11}}>Accès</label><select className="select-styled" style={{width:'100%'}}><option>🔓 Public</option><option>🔒 Abonnés</option></select></div></div></div></div>)}
      <div style={{background:'rgba(77,159,255,.06)',border:'1px solid rgba(77,159,255,.2)',borderRadius:'var(--radius-sm)',padding:14,marginTop:12,fontSize:12,color:'var(--text2)',display:'flex',gap:10}}><span style={{fontSize:18}}>💡</span><div>Publiez avec 0 épisode et ajoutez plus tard.</div></div>
      <div style={{display:'flex',justifyContent:'space-between',marginTop:18}}><button className="btn btn-outline" onClick={()=>setStep(1)}>← Retour</button><button className="btn btn-primary" onClick={()=>setStep(3)}>Suivant →</button></div>
    </div>}
    {step===3&&<div>
      <div className="upload-section-box"><div className="upload-section-title">📡 Diffusion</div><div style={{display:'flex',flexDirection:'column',gap:10}}>{[['Waiichia Podcast','Sur la plateforme',true],['Flux RSS','Spotify, Apple...',false]].map(([t,d,c])=><label key={t} style={{display:'flex',alignItems:'center',gap:10,cursor:'pointer',padding:10,background:'var(--bg2)',borderRadius:'var(--radius-sm)'}}><input type="checkbox" defaultChecked={c} style={{accentColor:'var(--gold)'}}/><div><div style={{fontSize:13,fontWeight:600}}>{t}</div><div style={{fontSize:11,color:'var(--text2)'}}>{d}</div></div></label>)}</div></div>
      <MonetBlock ok={ok} mode={pm} setMode={setPm} form={f} set={s} showBoth={true} preview={true} pvSec={pvS} setPvSec={setPvS}/>
      <div className="upload-section-box"><div className="upload-section-title">📡 Revenus complémentaires</div><div style={{display:'flex',flexDirection:'column',gap:8}}>{['💰 Pub (auto)','🎁 Tips'].map((t,i)=><label key={t} style={{display:'flex',alignItems:'center',gap:10,cursor:'pointer'}}><input type="checkbox" defaultChecked={i===0} style={{accentColor:'var(--gold)'}}/><div style={{fontSize:13}}>{t}</div></label>)}</div></div>
      <div style={{display:'flex',justifyContent:'space-between',gap:10,marginTop:8}}><button className="btn btn-outline" onClick={()=>setStep(2)}>← Retour</button><button className="btn btn-secondary">💾 Brouillon</button><button className="btn btn-primary" style={{flex:1,padding:13,fontSize:15}}>🚀 Publier</button></div>
    </div>}
  </div>)
}
function FEmission({ok}){
  const[step,setStep]=useState(1),[cp,setCp]=useState(''),[eps,setEps]=useState([{}]),[pm,setPm]=useState('free'),[pvS,setPvS]=useState(20),[f,sF]=useState({sp:'',rd:'',rw:'',rm:''})
  const s=(k,v)=>sF(p=>({...p,[k]:v}))
  const Steps=()=><div className="upload-steps-bar">{[{n:1,l:'Émission'},{n:2,l:'Épisodes'},{n:3,l:'Diffusion'}].map((x,i)=><div key={x.n} style={{display:'contents'}}>{i>0&&<div className="upload-step-sep"/>}<div className={`upload-step${step===x.n?' active':''}${step>x.n?' done':''}`} onClick={()=>setStep(x.n)}><span className="step-num">{step>x.n?'✓':x.n}</span><span>{x.l}</span></div></div>)}</div>
  return(<div className="upload-form-panel">
    <div className="upload-form-header"><div style={{fontSize:32}}>📺</div><div><div style={{fontFamily:'Syne,sans-serif',fontWeight:800,fontSize:18}}>Créer une Émission</div><div style={{fontSize:12,color:'var(--text2)'}}>Émission régulière ou série thématique</div></div></div>
    <Steps/>
    {step===1&&<div>
      <div className="form-group"><label className="label">🖼️ Visuel *</label><div className="cover-upload-row"><div className="cover-preview" onClick={()=>document.getElementById('cE').click()}><input type="file" id="cE" accept="image/*" style={{display:'none'}} onChange={e=>{const x=e.target.files[0];if(x)setCp(URL.createObjectURL(x))}}/>{cp?<img src={cp} alt=""/>:<><span>+</span><div style={{fontSize:10,marginTop:4}}>Ajouter</div></>}</div><div style={{fontSize:12,color:'var(--text2)'}}>1400×1400px</div></div></div>
      <div className="form-group"><label className="label">Nom *</label><input className="input-field" placeholder="Ex: Le Talk Africain..."/></div>
      <div className="form-row"><div className="form-group"><label className="label">Chaîne</label><input className="input-field" placeholder="Radio Komori FM"/></div><div className="form-group"><label className="label">Présentateur</label><input className="input-field" placeholder="Nom"/></div></div>
      <div className="form-row" style={{gridTemplateColumns:'1fr 1fr 1fr'}}><div className="form-group"><label className="label">Catégorie</label><select className="select-styled" style={{width:'100%'}}>{EMISSION_CATS.map(c=><option key={c}>{c}</option>)}</select></div><div className="form-group"><label className="label">Format</label><select className="select-styled" style={{width:'100%'}}><option>🎙️ Audio</option><option>🔴 Live</option><option>📻 RSS</option></select></div><div className="form-group"><label className="label">Langue</label><select className="select-styled" style={{width:'100%'}}>{LANGS.map(([c,l])=><option key={c}>{l}</option>)}</select></div></div>
      <div className="form-row" style={{gridTemplateColumns:'1fr 1fr 1fr'}}><div className="form-group"><label className="label">Pays</label><select className="select-styled" style={{width:'100%'}}>{COUNTRIES.slice(0,6).map(([c,l])=><option key={c}>{l}</option>)}</select></div><div className="form-group"><label className="label">Durée</label><select className="select-styled" style={{width:'100%'}}><option>~30 min</option><option>~45 min</option><option>~60 min</option><option>Variable</option></select></div><div className="form-group"><label className="label">Fréquence</label><select className="select-styled" style={{width:'100%'}}><option>Hebdomadaire</option><option>Mensuel</option><option>Quotidien</option></select></div></div>
      <div className="form-group"><label className="label">Description *</label><textarea className="textarea-field" rows="4" placeholder="Présentez votre émission..."/></div>
      <div style={{display:'flex',justifyContent:'flex-end',marginTop:18}}><button className="btn btn-primary" onClick={()=>setStep(2)}>Suivant →</button></div>
    </div>}
    {step===2&&<div>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:16}}><div style={{fontWeight:700,fontSize:15}}>Épisodes</div><button className="btn btn-outline btn-sm" onClick={()=>setEps(p=>[...p,{}])}>+ Épisode</button></div>
      {eps.map((_,i)=><div key={i} className="episode-block"><div className="episode-block-header"><div className="episode-num-badge" style={{background:'rgba(230,57,70,.15)',color:'var(--red)'}}>Ép. {i+1}</div><input className="input-field" placeholder="Titre *" style={{flex:1}}/>{eps.length>1&&<button className="episode-remove-btn" onClick={()=>setEps(p=>p.filter((_,j)=>j!==i))}>✕</button>}</div><div className="episode-block-body"><div className="upload-drop-zone" style={{padding:18,marginBottom:12}}><div style={{fontSize:20}}>🎙️</div><div style={{fontSize:13,fontWeight:600,marginTop:6}}>Fichier audio</div></div><div className="form-row" style={{gridTemplateColumns:'1fr 1fr 1fr 1fr'}}><div className="form-group"><label className="label" style={{fontSize:11}}>Saison</label><input className="input-field" type="number" defaultValue="1"/></div><div className="form-group"><label className="label" style={{fontSize:11}}>N°</label><input className="input-field" type="number" defaultValue={i+1}/></div><div className="form-group"><label className="label" style={{fontSize:11}}>Date</label><input className="input-field" type="date"/></div><div className="form-group"><label className="label" style={{fontSize:11}}>Heure</label><input className="input-field" type="time" defaultValue="20:00"/></div></div><div className="form-group"><label className="label" style={{fontSize:11}}>Invités</label><input className="input-field" placeholder="Noms..."/></div></div></div>)}
      <div style={{display:'flex',justifyContent:'space-between',marginTop:18}}><button className="btn btn-outline" onClick={()=>setStep(1)}>← Retour</button><button className="btn btn-primary" onClick={()=>setStep(3)}>Suivant →</button></div>
    </div>}
    {step===3&&<div>
      <div className="upload-section-box"><div className="upload-section-title">📡 Diffusion</div><div style={{display:'flex',flexDirection:'column',gap:10}}>{[['📺 Waiichia Émissions','Section Émissions',true],['🔴 Radio Live','Station partenaire',false],['📻 RSS','Externe',false]].map(([t,d,c])=><label key={t} style={{display:'flex',alignItems:'center',gap:10,cursor:'pointer',padding:10,background:'var(--bg2)',borderRadius:'var(--radius-sm)'}}><input type="checkbox" defaultChecked={c} style={{accentColor:'var(--gold)'}}/><div><div style={{fontSize:13,fontWeight:600}}>{t}</div><div style={{fontSize:11,color:'var(--text2)'}}>{d}</div></div></label>)}</div></div>
      <MonetBlock ok={ok} mode={pm} setMode={setPm} form={f} set={s} showBoth={true} preview={true} pvSec={pvS} setPvSec={setPvS}/>
      <div style={{display:'flex',justifyContent:'space-between',gap:10,marginTop:8}}><button className="btn btn-outline" onClick={()=>setStep(2)}>← Retour</button><button className="btn btn-secondary">💾 Brouillon</button><button className="btn btn-primary" style={{flex:1,padding:13,fontSize:15}}>🚀 Publier</button></div>
    </div>}
  </div>)
}
function FMedia({ok}){
  const[cp,setCp]=useState(''),[am,setAm]=useState('free'),[pvS,setPvS]=useState(30),[f,sF]=useState({fd:'',fw:'',fm:'',fy:''})
  const s=(k,v)=>sF(p=>({...p,[k]:v}))
  return(<div className="upload-form-panel">
    <div className="upload-form-header"><div style={{fontSize:32}}>📻</div><div><div style={{fontFamily:'Syne,sans-serif',fontWeight:800,fontSize:18}}>Soumettre un Flux Média</div><div style={{fontSize:12,color:'var(--text2)'}}>Radio FM, Web Radio, TV audio</div></div></div>
    <div style={{background:'rgba(245,166,35,.06)',border:'1px solid rgba(245,166,35,.25)',borderRadius:'var(--radius-sm)',padding:14,marginBottom:18,fontSize:12,color:'var(--text2)',display:'flex',gap:10}}><span style={{fontSize:18}}>🛡️</span><div>Flux média <strong>soumis à validation</strong> par Waiichia.</div></div>
    <div className="form-group"><label className="label">🖼️ Logo *</label><div className="cover-upload-row"><div className="cover-preview" onClick={()=>document.getElementById('cM').click()}><input type="file" id="cM" accept="image/*" style={{display:'none'}} onChange={e=>{const x=e.target.files[0];if(x)setCp(URL.createObjectURL(x))}}/>{cp?<img src={cp} alt=""/>:<><span>+</span><div style={{fontSize:10,marginTop:4}}>Logo</div></>}</div><div style={{fontSize:12,color:'var(--text2)'}}>Carré · 800×800 min</div></div></div>
    <div className="form-group"><label className="label">Nom station *</label><input className="input-field" placeholder="Radio Komori FM..."/></div>
    <div className="form-row" style={{gridTemplateColumns:'1fr 1fr 1fr'}}><div className="form-group"><label className="label">Type</label><select className="select-styled" style={{width:'100%'}}><option>📻 Radio FM</option><option>🌐 Web Radio</option><option>📺 TV Audio</option></select></div><div className="form-group"><label className="label">Genre</label><select className="select-styled" style={{width:'100%'}}><option>Varié</option><option>Twarab</option><option>Afrobeats</option><option>Info</option><option>Religieux</option></select></div><div className="form-group"><label className="label">Pays</label><select className="select-styled" style={{width:'100%'}}>{COUNTRIES.slice(0,8).map(([c,l])=><option key={c}>{l}</option>)}</select></div></div>
    <div className="form-group"><label className="label">Description</label><textarea className="textarea-field" rows="3" placeholder="Présentez votre station..."/></div>
    <div className="upload-section-box"><div className="upload-section-title">📡 Flux audio</div>
      <div className="form-group"><label className="label">URL stream *</label><input className="input-field" placeholder="https://stream.radio.com/live"/></div>
      <div className="form-row" style={{gridTemplateColumns:'1fr 1fr 1fr'}}><div className="form-group"><label className="label">Bitrate</label><select className="select-styled" style={{width:'100%'}}><option>128 kbps</option><option>192 kbps</option><option>256 kbps</option></select></div><div className="form-group"><label className="label">Codec</label><select className="select-styled" style={{width:'100%'}}><option>MP3</option><option>AAC</option><option>Opus</option></select></div><div className="form-group"><label className="label">Diffusion</label><select className="select-styled" style={{width:'100%'}}><option>🔴 24h/24</option><option>📅 Horaires</option></select></div></div>
    </div>
    <MonetFlux ok={ok} mode={am} setMode={setAm} form={f} set={s} pvSec={pvS} setPvSec={setPvS}/>
    <div className="upload-section-box" style={{borderColor:'rgba(230,57,70,.2)',background:'rgba(230,57,70,.03)'}}><div className="upload-section-title" style={{color:'var(--red)'}}>📋 Documents requis</div><div style={{display:'flex',flexDirection:'column',gap:12}}>{[['📄','Autorisation émission *'],['🏢','Registre commerce *'],['🪪','Pièce identité *'],['📑','Droits musicaux']].map(([ic,t])=><div key={t} className="doc-upload-row"><div className="doc-upload-label"><span style={{fontSize:16}}>{ic}</span><div style={{fontWeight:600,fontSize:13}}>{t}</div></div><label className="upload-mini-btn" style={{cursor:'pointer'}}>📎 PDF<input type="file" accept=".pdf,.jpg,.png" style={{display:'none'}}/></label></div>)}</div></div>
    <div className="upload-section-box"><div className="upload-section-title">✅ Conditions</div><div style={{display:'flex',flexDirection:'column',gap:10}}>{['Je certifie que les informations sont exactes.','Je respecte les CGU de Waiichia.','J\'accepte la modération.'].map(t=><label key={t} style={{display:'flex',alignItems:'flex-start',gap:10,cursor:'pointer'}}><input type="checkbox" style={{accentColor:'var(--gold)',marginTop:3}}/><div style={{fontSize:12,color:'var(--text2)',lineHeight:1.6}}>{t}</div></label>)}</div></div>
    <div className="upload-form-actions"><button className="btn btn-secondary">💾 Brouillon</button><button className="btn btn-primary" style={{flex:1,padding:13,fontSize:15}}>📤 Soumettre</button></div>
  </div>)
}
